export const metadata = {
  title: 'E-Voting',
  description: 'Generated by Next.js',
}

import Navbar from '@/components/Navbar'
import '@/styles/globals.css'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-webBg bg-cover bg-center">
        <Navbar />
        <main className="bg-webBg bg-cover bg-center h-full">{children}</main>
      </body>
    </html>
  )
}
